### PR TITLE
Provide programmatic access to error details

### LINKED ISSUE #25: Provide programmatic access to fields in FormatterDiagnostic
I know this project is in an early stage and you are probably working on the public API internally. However, I just stumbled upon this issue and wanted to leave a note.

One can retrieve the [diagnostics](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/FormatterException.java#L37) from a FormatterException, but a [FormatterDiagnostic](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/FormatterDiagnostic.java) doesn't provide programmatic access to the error information. This forces the programmer to parse the String returned by [toString()](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/FormatterDiagnostic.java#L39) (Effective Java Item 10).

### PR DESCRIPTION
**Pull request by sherter**
The toString() method in FormatterDiagnostic.java returns detailed
information about where an error occurred. This commit adds getter
methods to make this information available programmatically.

Closes #25

### CODE REVIEW

File: core/src/main/java/com/google/googlejavaformat/FormatterDiagnostic.java [hunk 1]
```diff
@@ -35,6 +35,26 @@ public FormatterDiagnostic(String filename, int lineNumber, int column, String m
...
+  public String filename() {
+    return filename;
+  }
+
+  /** Returns the line number on which the error occurred. */
+  public int line() {
+    return lineNumber;
+  }
+
+  /** Returns the column number on which the error occurred. */
```
Comment (cushon) [inline core/src/main/java/com/google/googlejavaformat/FormatterDiagnostic.java]: nit: maybe "Returns the 0-indexed column number ..." since it's not obvious which to expect.

**Comment by cushon** [comment]
Thanks, LGTM

File: core/src/main/java/com/google/googlejavaformat/FormatterDiagnostic.java (hunk 1 above)
Comment (sherter) [inline core/src/main/java/com/google/googlejavaformat/FormatterDiagnostic.java]: updated and squashed in 9159a98f8040ca40dcaddb577ffcf65af06af56f
